services:
  teams:
    image: otechdo/teams
    restart: always
    ports:
      - "8080:3000"
  adminer:
    image: adminer
    restart: always
    ports:
      - "8040:8080"
  gogs:
    image: gogs/gogs
    restart: always
    ports:
      - "8000:3000"